---
- name: Add sury's apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add sury's repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    state: present

- name: Install php-fpm and modules
  apt: name={{ item }} state=present
  with_items:
    - php7.2
    - php7.2-fpm
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-curl
    - php7.2-zip

- name: Disable default pool
  command: mv /etc/php/7.2/fpm/pool.d/www.conf /etc/php/7.2/fpm/pool.d/www.disabled creates=/etc/php/7.2/fpm/pool.d/www.disabled
  notify: restart web services

- name: Copy php-fpm configuration
  template: src=php-fpm.conf dest=/etc/php/7.2/fpm/pool.d/www.conf
  notify: restart web services

- name: Check if Composer is installed.
  stat: "path=/usr/local/bin/composer"
  register: composer_bin

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: yes
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    php composer-installer.php --filename=composer --install-dir=/usr/local/bin
    chdir=/tmp
  when: not composer_bin.stat.exists
